Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : atividade repeticao B
// Autor(a)    :Lucas sousa Da Luz
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
resultado: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
resultado <- 11
enuanto resultado < 1 faca

resultado <- resultado - 1

escreval (resultado)

fimenquanto








Fimalgoritmo