Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda nalon
// Descrição   : atividade 4
// Autor(a)    : lucas sousa da luz
// Data atual  : 13/12/2024
Var
// Seção de Declarações das variáveis 

 i, xx: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreva("Digite um valor: ")
   leia(xx)
   
   para i de 1 ate xx faca
      escreval(i)

   
   fimpara


Fimalgoritmo