Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda nalon
// Descrição   : atividade 2
// Autor(a)    : lucas sousa da luz
// Data atual  : 13/12/2024
Var
// Seção de Declarações das variáveis 

   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i de 10 ate 1 passo -1 faca

      escreval(i)
      
      
   fimpara



Fimalgoritmo