Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda nalon
// Descrição   : atividade 6
// Autor(a)    : lucas sousa da luz
// Data atual  : 13/12/2024
Var
// Seção de Declarações das variáveis 

i : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i de 15 ate 200 faca
   
      escreval("O quadrado de ", i, " é ", i * i)
      
   fimpara
   
Fimalgoritmo