Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda nalon
// Descrição   : atividade repeticao E
// Autor(a)    : luca sousa da luz
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

numero <- 2

repita

escreval(numero)

numero <- numero + 2

ate numero > 500




Fimalgoritmo