Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : atividade repeticao B
// Autor(a)    :Lucas sousa Da Luz
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
resultado: inteiro


Inicio



repita

resultado <- resultado + 1



escreval (resultado)

ate resultado = 10







Fimalgoritmo