Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2024
Var
numero, tabuada: inteiro



Inicio

numero <- 1

enquanto numero <= 10 faca

  tabuada <- (8 * numero)

    
    escreval ("A tabuada do 8: ", tabuada)
    
    numero <- numero + 1
    
    fimenquanto



Fimalgoritmo